In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [2]:
col_names = ['s2', 's3', 's4', 's7', 's11', 's12', 's13', 's14', 's15', 's17', 's20', 's21']
data_train = pd.read_csv('data/train.csv')
data_test = pd.read_csv('data/test.csv')

In [3]:

X_train =data_train[col_names]
y_train = data_train['ttf']
X_test = data_test[col_names]
y_test = data_test['ttf']

In [4]:
one = np.ones((X_train.shape[0], 1))
Xbar = np.concatenate((one, X_train), axis = 1)

one1 = np.ones((X_test.shape[0], 1))
Xbartest = np.concatenate((one1, X_test), axis = 1)

## áp dụng công thức

In [5]:
A = np.dot(Xbar.T, Xbar)
b = np.dot(Xbar.T, y_train)
w = np.dot(np.linalg.pinv(A), b)
# hệ số hồi quy
w

array([ 1.04180698e-02, -7.17788010e+00, -4.66888675e-01, -8.10874740e-01,
        7.27680847e+00, -3.92679746e+01,  1.12334451e+01,  1.53139461e+00,
       -6.20516567e-01, -1.27246340e+02, -2.00137617e+00,  2.11916350e+01,
        4.39509798e+01])

In [6]:
y_pred = np.sum(w*Xbartest,axis = 1)
y_pred

array([161.74478807, 121.21357856,  82.83013433,  96.17764469,
       114.94633657, 122.61440735, 131.31407882,  95.48847583,
       115.31566152, 117.29565118,  99.1407334 , 110.77350045,
        99.97921818, 114.19307335, 163.25001496, 137.53723026,
        80.88094533,  79.83648743, 122.03065741,  23.61989972,
       119.60300844, 143.99027253, 154.8345947 ,  33.90347005,
       136.89740772, 142.86302865, 130.0886211 , 113.98660033,
       126.2524686 ,  99.55627684,  12.52796076, 108.40458767,
       107.95709677,   6.2740615 ,  -0.56832364,  35.02654997,
        81.06814247,  69.97911583, 154.1923938 ,  37.66442349,
        93.11315726,  37.35593451,  78.11958066, 121.23522887,
        85.6962999 ,  67.09000611, 124.10889789, 120.37906766,
        20.6623091 , 127.79096635, 120.87558343,  50.60240878,
        40.7110501 , 169.47918738, 140.4092481 ,  36.01826618,
       105.33484358,  73.1810588 , 164.32407017, 117.18222134,
        52.82905576,  89.52644358,  85.04052456,  65.62

## áp dụng hàm có sẵn

In [7]:
regression = LinearRegression()
regression.fit(X_train, y_train)
# hệ số hồi quy
w1 = regression.coef_
w1

array([  -7.08623508,   -0.4596332 ,   -0.79636225,    7.09689047,
        -38.58435669,   10.95862007,  -13.49193377,   -0.63812921,
       -125.07937558,   -1.96193866,   20.74912844,   43.1220217 ])

In [8]:
w0 =  regression.intercept_ 
w0

36142.750327205395

In [9]:
y_pred = w0 + np.sum(w1*X_test,axis = 1)
y_pred

0     161.654513
1     121.517581
2      83.044663
3      96.480562
4     114.582613
         ...    
95    165.591838
96    107.704936
97     96.765383
98    161.148790
99      4.949056
Length: 100, dtype: float64

In [10]:
y_pred = regression.predict(X_test)
y_pred

array([161.65451256, 121.51758119,  83.04466309,  96.48056154,
       114.58261333, 121.6313789 , 131.08481981,  95.87029293,
       114.51148866, 117.40683296,  98.90946703, 111.47288134,
        99.70624192, 114.79500736, 162.06372836, 137.04400232,
        81.52368755,  79.14452195, 122.38472551,  23.6640085 ,
       118.99599033, 143.38694699, 154.4773464 ,  33.6899708 ,
       137.06222127, 143.67465931, 129.58768515, 113.90708685,
       126.21729615,  99.44993644,  12.19215283, 108.12518069,
       108.0651611 ,   6.59709218,  -0.60986656,  34.81273722,
        81.51539197,  69.39779056, 154.6695948 ,  37.93732071,
        92.70554016,  36.91179697,  78.0359954 , 121.29685799,
        85.43464068,  67.38759629, 123.7073496 , 119.45573644,
        20.81957288, 127.99232267, 120.76360422,  50.63997706,
        41.57263569, 170.131978  , 140.8790971 ,  36.25243425,
       104.37003496,  72.69633097, 164.06834611, 117.60016632,
        52.64111105,  89.85904457,  84.71594426,  66.27

In [11]:
# R bình % của dự đoán
r_sq = regression.score(X_test, y_test)
r_sq 

0.41504559932988916

In [12]:
metrics.mean_absolute_error(y_test, y_pred)

25.44318539541935

In [13]:
np.sqrt(metrics.mean_squared_error(y_test, y_pred))

31.78269925452264

In [14]:
df = pd.DataFrame({'thực': y_test, 'dự đoán': y_pred})
df

thực     dự đoán
0    112  161.654513
1     98  121.517581
2     69   83.044663
3     82   96.480562
4     91  114.582613
..   ...         ...
95   137  165.591838
96    82  107.704936
97    59   96.765383
98   117  161.148790
99    20    4.949056

[100 rows x 2 columns]

In [25]:
from sklearn.ensemble import RandomForestRegressor
regr = RandomForestRegressor()
regr.fit(X_train, y_train)
RandomForestRegressor(...)
y_pred = regr.predict(X_test)
y_pred

array([179.91, 153.67,  64.85, 111.95, 137.04, 124.22, 129.8 , 109.  ,
       129.63, 132.56,  67.31,  78.65,  99.68, 134.4 , 176.97, 111.79,
        55.8 ,  72.68, 133.82,  24.92,  65.95, 152.7 , 178.54,  23.38,
       145.7 , 131.2 , 159.49, 128.06, 157.82, 112.92,  23.46,  57.02,
       126.47,   7.  ,   7.65,  23.95,  49.19,  47.19, 146.21,  30.7 ,
        72.1 ,  21.21,  70.73, 149.8 ,  87.8 ,  62.45, 136.41, 121.19,
        14.65, 136.57, 147.26,  29.02,  32.75, 157.84, 143.19,  14.67,
       108.07,  59.62, 164.05, 137.18,  43.75,  58.14,  66.3 ,  54.65,
       175.28,  14.4 , 156.68,  18.27, 154.04, 120.44, 143.41,  67.37,
       183.74, 119.26, 167.1 ,  13.86,  31.97, 211.78, 135.93, 104.27,
         7.14,   8.87, 135.63,  50.64, 141.16,  86.85, 137.62, 155.72,
       139.71,  40.91,  26.77,  22.77,  42.95,  50.75, 153.21, 172.49,
        83.93,  85.18, 156.59,  16.84])

In [23]:
r_sq = regr.score(X_test, y_test)
r_sq 

0.3318243415715928